version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000

  backend: 
    depends_on:
      - db
    build: ./backend
    ports: 
      - 3020:3020

  db: 
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "Postgres2022!"

